#! /bin/sh

NAME=$(basename $0)

MINIMAL=0
VERBOSE=0

# -------------------------------------------------------------------

print_help()
{	
	cat <<- EOF
	Usage: $NAME [OPTIONS]

	  Options:
	  -m     --minimal    Minimal mode
	  -v     --verbose    Verbose mode
	  -h -?  --help       Print usage instructions
	EOF
}

print_ascii() 
{ 
cat << EOF
     ________________________________         
    /                                "-_          
   /      .  |  .                       \          
  /      : \ | / :                       \         
 /        '-___-'                         \      
/_________________________________________ \      
     _______| |________________________--""-L 
    /       F J                              \ 
   /       F   J                              L
  /      :'     ':                            F
 /        '-___-'                            / 
/_________________________________________--"  

EOF
}

print_separator() { printf "%*s\n" 60 | tr ' ' '-' ; }

log()
{
	[ "$2" = 0 ] && printf "\e[m[\e[31m-\e[m]"
	[ "$2" = 1 ] && printf "\e[m[\e[32m+\e[m]"
	[ "$2" = 2 ] && printf "\e[m[\e[33m!\e[m]"
	
	[ -z $2 ] && printf "\e[m[*]"

	printf "\x20$1\n"
}

evaluate_arguments()
{
	for arg in $@
	do
		case $arg in
			-h|-\?|--help) print_help ; exit ;;

			-m|--minimal) MINIMAL=1 ;;
			-v|--verbose) VERBOSE=1 ;;
		esac
	done
}

# -------------------------------------------------------------------

evaluate_arguments $@

# Example

print_ascii

log "Error" 0
log "Success" 1
log "Warning" 2
log "Information"

echo

print_separator

echo

echo "Logging example: "

echo

log "Could not establish connection to node" 0
log "Compilation complete - Total time: 00:01:17" 1
log "Low battery life" 2
log "Extracting buffer..."
log "Buffer extracted: " 1

cat << EOF
	
	0x65 0x6e 0x67 0x69 0x6e 0x65 
	0x65 0x72 0x2d 0x39 0x39 0x62

	0x32 0x30 0x32 0x30

EOF

read -p ">>> " message

echo

log "Message received: $message" 1

echo

log "Exiting..."

echo
