#! /bin/sh

# engineer-99b

# -------------------------------------------------------------------

NAME=$(basename $0)

# -------------------------------------------------------------------

MINIMAL=0

VERBOSE=0

# -------------------------------------------------------------------

print_ascii() { cat << EOF
	 ________________________________         
	/                                "-_          
   /      .  |  .                       \          
  /      : \ | / :                       \         
 /        '-___-'                         \      
/_________________________________________ \      
	 _______| |________________________--""-L 
	/       F J                              \ 
   /       F   J                              L
  /      :'     ':                            F
 /        '-___-'                            / 
/_________________________________________--"  
EOF
}

print_help()
{	
	cat <<- EOF
	Usage: $NAME [OPTIONS]

	  Options:
	  -m     --minimal    Minimal mode
	  -v     --verbose    Verbose mode
	  -h -?  --help       Print usage instructions
	EOF

	exit
}

log()
{
	[ "$2" = 0 ] && printf "\e[m[\e[31m-\e[m]"
	[ "$2" = 1 ] && printf "\e[m[\e[32m+\e[m]"
	[ "$2" = 2 ] && printf "\e[m[\e[33m!\e[m]"
	
	[ -z $2 ] && printf "\e[m[*]"

	printf "\x20$1\n"
}

evaluate_arguments()
{
	for arg in $@
	do
		case $arg in
			-h|-\?|--help) print_help ;;

			-m|--minimal) MINIMAL=1 ;;
			-v|--verbose) VERBOSE=1 ;;
		esac
	done
}

# -------------------------------------------------------------------

evaluate_arguments $@

# Example

print_ascii

echo ""
echo $NAME
echo ""

log "Error" 0
log "Success" 1
log "Warning" 2
log "Information"

echo ""

log "Could not establish connection to node" 0
log "Compilation complete - Total time: 00:34:56" 1
log "Battery life is running low" 2
log "Uploading payload to target..."

echo ""
