#! /bin/sh

# engineer-99b

# -------------------------------------------------------------------

NAME=$(basename $0)

HELP=$(cat << EOL
Usage: $NAME [OPTIONS]

  Options:
  -m     --minimal    Minimal mode
  -h -?  --help       Print usage instructions
EOL
)

# -------------------------------------------------------------------

MINIMAL=0

# -------------------------------------------------------------------

evaluate_arguments()
{
	for arg in $@
	do
		case $arg in
			-h|-\?|--help) echo "${HELP[@]}" ; exit ;;

			-m|--minimal) MINIMAL=1 ;;
		esac
	done
}

main()
{
	echo $NAME
}

# -------------------------------------------------------------------

evaluate_arguments $@

main
